### PR TITLE
HC-302 Add capability to propagate info and/or warning message up to the UI for successful jobs

### PR DESCRIPTION
**Pull request by DustinKLo**
related ticket: https://hysds-core.atlassian.net/browse/HC-302

This PR is dependent on https://github.com/hysds/hysds/pull/122

### CODE REVIEW

**Comment by mcayanan** [comment]
Initial testing with the purge job:

image

Let me do a bit more testing on this before calling it good.

**Comment by pymonger** [comment]
@mcayanan: sounds good. I'll defer to you. Otherwise LGTM.

**Comment by mcayanan** [comment]
Was able to see the short and message details:

image

image

**Review by mcayanan — APPROVED** [review]
The UI looks good to me.

**Pull request merged**
